modLoader="javafml"
loaderVersion="[27,)"
logoFile="${mod_icon}"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_name}"
    displayURL="${mod_url}"
    issueTrackerURL="${mod_url}/issues"
    authors="${mod_author}"
    description='''
    ${mod_description}
    '''
