modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/blackducksoftware/ducky-mod/issues"
logoFile="${mod_icon}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors="${mod_author}"
description='''
${mod_description}
'''
